package enums;

public enum CharacterSubClass {
	// barbarian
	Cannibal,
	PathOfTheAncestralGuardian,
	PathOfTheBattleRager,
	PathOfTheBerserker,
	PathOfTheStormHerald,
	PathOfTheTotemWarrior,
	PathOfTheZealot,
	// bard
	CollegeOfGlamour,
	CollegeOfLore,
	CollegeOfSatire,
	CollegeOfSwords,
	CollegeOfValor,
	CollegeOfWhispers,
	// cleric
	ArcanaDomain,
	DeathDomoain,
	CityDomain,
	ForgeDomain,
	GraveDomain,
	KnowledgeDomain,
	LifeDomain,
	LightDomain,
	NatureDomain,
	ProtectionDomain,
	TempestDomain,
	TrickeryDomain,
	WarDomain,
	// druid
	CircleOfDreams,
	CircleOfTheLand,
	CirleOfTheMoon,
	CircleOfSpores,
	CircleOfTwilight,
	// fighter
	ArcaneArcher,
	Banneret,
	Brute,
	Cavlier,
	Champion,
	EldritchKnight,
	Knight,
	Samurai,
	Sharpshooter,
	// monk
	WayOfTheDrunkenMaster,
	WayOfTheFourElements,
	WayOfTheKensel,
	WayOfTheLongDeath,
	WayOfTheOpenHand,
	WayOfShadow,
	WayOfTheSunSould,
	WayOfTranquility,
	// paladin
	OathOfTheAncients,
	OathOfConquest,
	OathOfTheCrown,
	OathOfDevotion,
	OathOfRedemption,
	OathOfTreachery,
	OathOfVengeance,
	Oathbreaker,
	// ranger
	BeastMaster,
	GloomStalker,
	HorizonWalker,
	Hunter,
	MonsterSlayer,
	PrimevalGuardian,
	// rogue
	ArcaneTrickster,
	Assassin,
	Inquisitive,
	Mastermind,
	Scout,
	Swashbuckler,
	Thief,
	// sorcerer
	DivineSoul,
	DraconicBloodline,
	SeaSorcery,
	ShadowMagic,
	StoneSorcery,
	StormSorcery,
	WildMagic,
	// warlock
	TheArchfey,
	TheCelestial,
	TheFiend,
	GhostInTheMachine,
	TheGreatOldOne,
	TheHexblade,
	TheRavenQueen,
	TheSeeker,
	TheUndying,
	Artificer,
	Bladesinging,
	LoreMastery,
	// wizard
	SchoolOfAbjuration,
	SchoolOfConjuration,
	SchoolOfDivination,
	SchoolOfEnchantment,
	SchoolOfEvocation,
	SchoolOfIllusion,
	SchoolOfInvention,
	SchoolOfNecromancy,
	SchoolOfTransmutation,
	Technomancy,
	Theurgy,
	WarMagic,
	// default
	Not_Applicable
}
